name: rafeeqa
description: "A little support for the biggest journey."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  flutter_screenutil: ^5.9.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  smooth_page_indicator: ^3.0.0
  hydrated_bloc: ^11.0.0
  flutter_bloc: ^9.1.1
  path_provider: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  background_color_ios: Theme.backgroundApp
  image_path: Assets.appLogo
  min_sdk_android: 21
  adaptive_icon_background: Theme.backgroundApp
  adaptive_icon_foreground: Assets.appLogo
  adaptive_icon_foreground_inset: 25

flutter_native_splash:
  android: true
  ios: true
  color: Theme.backgroundApp
  image: Assets.splashNative
  fullscreen: true
  android_12:
    color: Theme.backgroundApp
    image: Assets.splashNative
    icon_background_color: "#FFF5F7"
flutter_intl:
  enabled: true
